version: '3.8'
services:
    mysql-standalone:
        image: 'mysql:5.7'
        env_file: ./.env
        environment:
            - MYSQL_ROOT_USER=$MYSQLDB_ROOT_USER
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        networks:
            - common-network
        volumes:
            - mysql-standalone:/var/lib/mysql

    springboot-docker-container:
        depends_on:
            -   mysql-standalone
        build: ../employee-managment
        env_file: ./.env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://mysql-standalone:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
                "spring.datasource.username" : "$MYSQLDB_USER",
                "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
              }'
        networks:
            - common-network
        volumes:
            - .m2:/root/.m2

volumes:
    mysql-standalone:
networks:
    common-network:
        driver: bridge